#!/bin/bash

MODE=${1:-prod}
if [[ "$MODE" == "dev" ]]; then
	echo "🔧 Build mode: DEV (no minify, console enabled)"
	export BUILD_MODE=dev
else
	echo "🚀 Build mode: PROD (minified, console dropped)"
	unset BUILD_MODE
fi

echo "🦀 Building Hello World Extension with Rust/WASM..."
echo ""

# Build WASM module
echo "Step 1: Building WASM module..."
cd wasm_mod
wasm-pack build --target web --release --out-dir ../extension/js/wasm
cd ..

echo ""
echo "Step 2: Cleaning up unnecessary files..."
# Remove unnecessary files generated by wasm-pack
rm -f extension/js/wasm/.gitignore
rm -f extension/js/wasm/package.json
rm -f extension/js/wasm/README.md

echo ""
echo "Step 3: Building content script with esbuild..."
# Pass through mode to node via env (build-content.js also reads CLI args)
if [[ "$MODE" == "dev" ]]; then
	npm run build:content -- dev
else
	npm run build:content
fi

echo ""
echo "✅ Build complete!"
echo ""
echo "📦 Extension files are in the 'extension/' folder"
echo ""
echo "To load in Chrome/Brave:"
echo "1. Go to chrome://extensions/"
echo "2. Enable 'Developer mode'"
echo "3. Click 'Load unpacked'"
echo "4. Select the 'extension' folder"
echo ""
echo "To load in Firefox:"
echo "1. Go to about:debugging#/runtime/this-firefox"
echo "2. Click 'Load Temporary Add-on'"
echo "3. Select extension/manifest.json"
