#!/bin/bash

echo "🦀 Building Hello World Extension with Rust/WASM..."
echo ""

# Build WASM module
echo "Step 1: Building WASM module..."
cd wasm_mod
wasm-pack build --target web --release --out-dir ../extension/js/wasm
cd ..

echo ""
echo "Step 2: Cleaning up unnecessary files..."
# Remove unnecessary files generated by wasm-pack
rm -f extension/js/wasm/.gitignore
rm -f extension/js/wasm/package.json
rm -f extension/js/wasm/README.md

echo ""
echo "Step 3: Building content script with esbuild..."
npm run build:content

echo ""
echo "✅ Build complete!"
echo ""
echo "📦 Extension files are in the 'extension/' folder"
echo ""
echo "To load in Chrome/Brave:"
echo "1. Go to chrome://extensions/"
echo "2. Enable 'Developer mode'"
echo "3. Click 'Load unpacked'"
echo "4. Select the 'extension' folder"
echo ""
echo "To load in Firefox:"
echo "1. Go to about:debugging#/runtime/this-firefox"
echo "2. Click 'Load Temporary Add-on'"
echo "3. Select extension/manifest.json"
