import initWasmModule, { show_alert } from "./wasm/wasm_mod.js";

// the initializer is generated by wasm_pack
(async () => {
  await initWasmModule();
})();

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg.action === "process") {
    const result = show_alert(msg.data);
    sendResponse({ result });
  }
});
